language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - opam
    - ocaml-native-compilers
install: sh -ex .travis-install.sh
cache:
  directories:
  - ${HOME}/.opam
script: sh -ex .travis-ci.sh
matrix:
  include:
#  - env: OCAML_VERSION=system
#  - env: OCAML_VERSION=3.12.1
#  - env: OCAML_VERSION=4.01.0
  - env: OCAML_VERSION=4.02.3
#  - env: OCAML_VERSION=4.03.0
# - env: OCAML_VERSION=lint
#  allow_failures:
#  - env: OCAML_VERSION=lint
