
include autoconf/Makefile.config

all: ocp-build-build

install: ocp-build-install

clean: ocp-build-clean

distclean: clean ocp-distclean
	find . -name '*~' -exec rm -f {} \;

include autoconf/Makefile.rules

